### ISSUE TITLE
Authentication etc. failures with comet incorrectly put connection into 'disconnected' state (should be 'failed')

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#101]
Using websockets:
```
Ably: ConnectionManager.chooseTransport():  ably.js:4067:46
connecting ably-sandbox.js:70:3
Ably: Transport.onChannelMessage(): error; connectionKey = undefined; err = {"message":"No application found with id foo","code":40400,"statusCode":404}

> realtime.connection.state
"failed"
```

Using comet:
```
Ably: ConnectionManager.chooseTransport(): Unexpected error establishing transport; err = {"statusCode":404,"code":40400,"message":"No application found with id foo"} ably.js:4067:46
Ably: ConnectionManager.connectImpl(): Connection attempt failed with error; err = [ErrorInfo: No application found with id foo; statusCode=404; code=40400] ably.js:4067:46
disconnected ably-sandbox.js:70:3

> realtime.connection.state
 "disconnected"
```

**Comment by SimonWoolf** [comment]
Also same problem with websockets iff using tokenauth.

same behaviour on new-upgrade branch

**Comment by SimonWoolf** [comment]
@paddybyers the problem with setting `fatal` to `err.statusCode < 500` is that when all the available transports fail just for internet/502-type problems, `chooseTransportForHost`, having run through all the transports and gotten (say) 502s from each of them, ends up calling the callback with a (404, 80000): https://github.com/ably/ably-js/blob/master/common/lib/transport/connectionmanager.js#L198,L204 -- but in that case we want the state to be `disconnected` and not `failed`.

Could you clarify your objection to `var fatal = err.code >= 40000 && err.code < 50000`? The only recoverable one in there is 40140, which is dealt with in a separate clause above: https://github.com/ably/ably-js/blob/797fe896df373f9e783325da33440bd95acc67d6/common/lib/transport/connectionmanager.js#L642

**Comment by paddybyers** [comment]
> having run through all the transports and gotten (say) 502s from each of them, ends up calling the callback with a (404, 80000): https://github.com/ably/ably-js/blob/master/common/lib/transport/connectionmanager.js#L198,L204 -- but in that case we want the state to be disconnected and not failed.

The problem with this bit of code is that it doesn't distinguish between:

- all attempted hosts failed because they were all unreachable or broken, which is really a 500;
- the given transports aren't functional in this user agent, which is really a 400.

The issue is that the library can't really distinguish between these cases if it attempts to connect to the host and it gets nothing back. I think in this case the right thing to do is really give the client the benefit of the doubt and make this a 500 error.

> Could you clarify your objection to doing it by statusCodes, var fatal = err.code >= 40000 && err.code < 50000?

I don't object to this AFAIK.

**Comment by SimonWoolf** [comment]
OK; raised a pr for that one: https://github.com/ably/ably-js/pull/112.

If doing it by the full codes then it doesn't matter whether unreachable-transport is 404 or 500 as long as the full one is 80000; want me to change it anyway?

**Comment by paddybyers** [comment]
> Could you clarify your objection to doing it by statusCodes

OK, I think I was confused.
There are error responses (eg from ELB) where we will only get a status code. Don't we have to use that as the test?

**Comment by SimonWoolf** [comment]
AFAICT `connectImpl` mostly doesn't get those 'raw' - if they result in the transport failing then chooseTransport wraps them in 404/80000. When they aren't, they'll have no `code`, so will fail the test, and go into `disconnected` rather than `failed`. But that's what we want, isn't it? I.e. defaulting to `disconnected` unless we're sure the failure is realtime giving us a definitely unrecoverable error code.

**Comment by paddybyers** [comment]
Unfortunately I think we have a couple of codes outside the 40000 range that will signify a fatal error:

````
"80015": "incompatible connection parameters"
"80030": "client restriction not satisfied",
````

But overall I support the idea that we use code ranges instead of status codes, provided that we're handling the case of responses that have no code. We would have to move these specific codes to the 40000 range.

Does that do what we need?

And shouldn't this test: https://github.com/ably/ably-js/blob/master/common/lib/transport/connectionmanager.js#L224 then be using codes as well? Or `(code === undefined && statusCode < 500) || (code < 50000)` or something?

**Comment by SimonWoolf** [comment]
Tried shoving everything into a helper that takes an options param - https://github.com/ably/ably-js/pull/112/files . This does what we want, and at least the logic's now in one place rather than over four slightly different tests -- but it's ugly/inelegant as sin. Going to come back to it later and refactor it a bit, so don't merge yet.

**Comment by paddybyers** [comment]
ug

we should discuss the circumstances that require that param.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/112/files
