### ISSUE TITLE
Errors in event callbacks are swallowed

### ISSUE THREAD

**Issue by JCB-K** [ably/ably-js#1015]
I noticed that errors in event callbacks are swallowed:

```js
const handler = (msg) => {
  console.log(notDefined);
}

handler(); // Uncaught ReferenceError
channel.subscribe(handler) // this will fail silently when a message comes in
```

Is this expected behaviour? If so, is there a way to read these errors and respond to them?

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2369) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hey @JCB-K, thanks for raising this. Currently the library should emit an error message to the console when this happens, I just tested in Chrome and NodeJS and it seems to work. Let me know if this isn't happening on whatever platform you're using and I'll look into it.

As for being able to handle listener errors programmatically I'm not sure if there's any good way to do this. Since listeners can execute more than once you can't use promises - the only way we could provide an API for this is to use another listener for subscription errors but then you'd just have the same problem if the error listener threw an exception.

I think the best approach here is to ensure that you handle all listener exceptions yourself. If you find yourself doing this a lot it might be worth wrapping `channel.subscribe` with something like the snippet below:
```ts
function susbcribeWithErrorHandler(channel, listener, errorHandler) {
  return channel.subscribe(msg => {
    try {
      listener(msg);
    } catch (err) {
      errorHandler(err, msg);
    }
  });
}
```

**Comment by owenpearson** [comment]
> Do I understand correctly that the trade-off here is that if you don't catch errors in message handlers then they would stop executing as soon as one of them hits an error?

Not sure if I understand this, sorry. Whether we catch errors in message handlers or not, they will stop executing once an exception is thrown. The tradeoff I was describing above is really about what we do with the error after we've caught it - as far as I know there's not really any sensible way to surface that to the user other than just logging it.

But yes, using a custom logger here seems like the right idea 👍

**Comment by JCB-K** [comment]
Yeah we're on the same line here - I just didn't put it into words clearly 😀. Thanks for the info 👍
