### ISSUE TITLE
Auth differences between ably-js and ably-ruby

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#116]
- if you call `request_token` with a single argument (normally takes both `auth_options` and `token_params`), ably-ruby assumes it's the `auth_options`, ably-js [assumes it's `tokenParams`](https://github.com/ably/ably-js/blob/master/common/lib/client/auth.js#L210).

- if you supply `tokenParams`, ably-js assumes they [replace](https://github.com/ably/ably-js/blob/master/common/lib/client/auth.js#L216) existing token params, ably-ruby [merges them](https://github.com/ably/ably-ruby/blob/master/lib/ably/auth.rb#L157).

@mattheworiordan @paddybyers

(I marginally prefer ably-ruby behaviour in both cases: for the first, having tokenOptions sometimes be the second argument and sometimes be the first seems nonideal; for the second, someone might want to modify the ttl, but would still assume it'd use the clientId the lib was initialized with).

**Comment by mattheworiordan** [comment]
I agree ;)

**Comment by paddybyers** [comment]
I agree on the second point, not sure I agree on the first :)

**Comment by mattheworiordan** [comment]
@paddybyers, the `requestToken` behaviour that expects `authOptions` as the first param and `tokenParams` as the second, but `tokenParams` as the first if only one arguments is provided is very much a Javascript way of doing things.  If `authOptions` were indeed "inferior", then they should have been the second argument so that we can avoid this ambiguity.  I vote we change it and keep the argument ordering consistent across all languages, thoughts?

**Comment by paddybyers** [comment]
> If authOptions were indeed "inferior", then they should have been the second argument so that we can avoid this ambiguity.

Yes, agreed.

> I vote we change it

"it" is the precedence (ie match how Ruby prefers `authOptions`) or the argument order?

I do think that `authOptions` is inferior, because when you're requesting a token you're primarily, I think, expecting to pass the params relating to that specific token, ie `tokenParams`. I think `authOptions` is subsidiary and is only there as a convenience for values that different/augment the options given at initialisation. I'm not sure, however, that it is worth changing the argument order at this stage.

**Comment by mattheworiordan** [comment]
Superseded by https://github.com/ably/ably-js/issues/137
