### ISSUE TITLE
NextJS 13 w/App Router - How to Prevent Server-Side Render?

### ISSUE THREAD

**Issue by starlight-akouri** [ably/ably-js#1431]
I am struggling to figure out how to structure my app/components. No matter what I do, NextJS tries to connect to Ably on the server-side.

I've tried:
- Wrapping the component in `import dynamic from 'next/dynamic'`;
- Adding a window type check:
```
   if (typeof window !== undefined) {
  // prevent nextjs from running this code serverside:
  realtime.connection.on("connecting", () => {
    console.log("Attempting to connect here..");
  });
  realtime.connection.on("connected", () => {
    console.log("Connected to Ably");
  });
  const estimateChannel = realtime.channels.get(props.estimate.id);
  estimateChannel.subscribe("phoneOnline", (message) => {
    console.log("Received message ", message);
    setOpenedOnPhone(true);
  });
   }
```

However, I am still getting "attempting to connect here..." on my server-side logs.   

```
17:46:17.553 Ably: Auth.requestToken(): token request signing call returned error; err = Error: `input` must not start with a slash when using `prefixUrl`
Attempting to connect here..
```

I understand that adding `next/dynamic` around the component will cause just the component to be rendered client-side only, but how do I get the javascript that's actually running on the component to also ONLY run client-side?

**Comment by owenpearson** [comment]
Hey @starlight-akouri, thanks for reporting this! I've tested this locally with a nextjs app and am able to prevent component javascript from running using `next/dynamic`. Do you have a more complete example of how you're using it?

The way I'm using `next/dynamic` is this:
```ts
import dynamic from 'next/dynamic';

const DynamicComponent = dynamic(() => import('./path/to/ably/component'), {
  ssr: false,
})

export default DynamicComponent;
```

Also, as a more temporary fix, you should be able to avoid this error by using a fully qualified url (with a hostname and scheme) as your `authUrl`, rather than a path beginning with a `/` character.

**Comment by matannahmani** [comment]
this is not fixed yet.
i tried the following:
```"use client";
import { AblyProvider as AblyProviderBase } from "ably/react";
import { useEffect, useState } from "react";
import { ablyClient } from "~/shared/ably/ably";

export default function AblyProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loaded, setLoaded] = useState(false);
  useEffect(() => {
    setLoaded(true);
  }, []);
  if (!loaded) return children;
  return <AblyProviderBase client={ablyClient}>{children}</AblyProviderBase>;
}
```

and then consume it with:
```
import dynamic from "next/dynamic";
const AblyProvider = dynamic(
  () => import("~/components/providers/AblyProvider"),
  {
    ssr: false,
  },
);
```

but i keep getting errors and page crash:
```
 ⨯ ReferenceError: window is not defined
    at __webpack_require__ (/home/matan/code/down-to-eat/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/home/matan/code/down-to-eat/.next/server/edge-runtime-webpack.js:330:21)
    at __webpack_require__ (/home/matan/code/down-to-eat/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/home/matan/code/down-to-eat/.next/server/edge-runtime-webpack.js:330:21)
```

**Comment by matannahmani** [comment]
managed to fix this, I think it would be good to make an official documentation of basic implementation.
my issue was the ablyClient, it must be initiated inside a client component inside the react tree.
to fix it you can create a provider as follows:
```
export default function AblyProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [client, _] = useState(
    new Realtime.Promise({
      key: env.NEXT_PUBLIC_ABLY_CLIENT_API_KEY,
    }),
  );
  return <AblyProviderBase client={client}>{children}</AblyProviderBase>;
}
```

**Comment by owenpearson** [comment]
@matannahmani, the "window is not defined" error message indicates that something is trying to access the `window` object on the server side, but if loaded correctly, ably-js works fine on NodeJS without accessing the `window` object. The stack trace in your comment doesn't appear to point to anything ably-related but if you believe your webpack config is loading the web version of ably-js on the server side then it's more likely an issue with your webpack config. If you're sure it's an issue with ably-js feel free to share a minimal repro and I can take a look 🙂 

I'm gonna close this issue for now, since guidance on how to ensure code runs on the client side should come from the react frameworks themselves and unfortunately it's not really practical for us to provide examples on how to do this for each framework.
