### ISSUE TITLE
Type inference issue in react hooks

### ISSUE THREAD

**Issue by abhi-abhiram** [ably/ably-js#1488]
There is a issue with type inference on the return type for the **useChannel** hook.

![Screenshot 2023-11-08 at 3 59 07 PM](https://github.com/ably/ably-js/assets/68490325/66d521e8-0eca-4e82-88e5-8ed2d5ba9e02)

![Screenshot 2023-11-08 at 4 01 01 PM](https://github.com/ably/ably-js/assets/68490325/540bd941-a49b-45b2-8409-a3d23703a8d7)

**Comment by owenpearson** [comment]
Hey @abhi-abhiram I just tried this on the latest version of the `ably` package and the typing works fine for me.

The error you're seeing is strange because your vscode language server is correctly picking up the type of channel as `Types.RealtimeChannelPromise`, so it seems like it's the `@typescript-eslint` parser getting it wrong.

One thing I notice is that you're incorrectly providing the `message` callback param type as `string` when it should be `Ably.Types.Message` - maybe changing that to the correct typing will fix the issue? Let me know if that doesn't work

**Comment by abhi-abhiram** [comment]
Thanks for the quick reply. I tried adding correct type it didn't worked. Seems like typescript inteligence is also not able to pick it up.

![Screenshot 2023-11-08 at 4 37 24 PM](https://github.com/ably/ably-js/assets/68490325/5d1f633d-1eb9-4f1a-857f-267e290cd6d0)

But it is able to pick type for channel. May be it is a typescript bug

![Screenshot 2023-11-08 at 4 38 36 PM](https://github.com/ably/ably-js/assets/68490325/5523183e-030d-4ce8-b4ce-9f5035c724c3)

**Comment by abhi-abhiram** [comment]
Thanks for the quick reply. I tried adding correct type it didn't worked. Seems like typescript inteligence is also not able to pick it up.

![Screenshot 2023-11-08 at 4 37 24 PM](https://github.com/ably/ably-js/assets/68490325/5d1f633d-1eb9-4f1a-857f-267e290cd6d0)

But it is able to pick type for channel. May be it is a typescript bug

![Screenshot 2023-11-08 at 4 38 36 PM](https://github.com/ably/ably-js/assets/68490325/5523183e-030d-4ce8-b4ce-9f5035c724c3)

**Comment by abhi-abhiram** [comment]
It is working when I change ` import { Types } from '../../../../../ably.js';` to `import { Types } from '../../../../ably';`

**Comment by owenpearson** [comment]
@abhi-abhiram that's interesting, are you making that change in `useChannel.d.ts` in your node_modules directory?

**Comment by owenpearson** [comment]
Hey @abhi-abhiram, just to let you know we've fixed this issue now in version 1.2.48, let us know if you have any further issues 🙂
