### ISSUE TITLE
Project does not build with a current (LTS) version of Node (18+)

### ISSUE THREAD

**Issue by scottned** [ably/ably-js#1493]
When building the project with Node 18, I get this error:

```shell
Running "webpack:all" (webpack) task
10% [3] building 0/1 modules 1 active .../snedderman/src/ably-js/src/platform/web/index-webworker.tsFatal error: error:0308010C:digital envelope routines::unsupported
npm ERR! code 3
npm ERR! path /Users/snedderman/src/ably-js
```

This error can currently be resolved by [downgrading to Node 16](https://stackoverflow.com/a/69699772/226884) which is no longer in [support](https://endoflife.date/nodejs).

Please update the project so it can be built with current versions of Node.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4187) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hey @scottned thanks for reaching out!

Unfortunately this is an issue with webpack v4 which we're planning on moving away from in the near future but we're not there yet. For development we've been using the legacy openssl provider to build the library in node 18 when needed, would this work for you? Would also be good to know what you're building the library for - ie. are you installing it via git rather than npm?

**Comment by owenpearson** [comment]
Ah I see, sorry for the inconvenience - if the error you're seeing is `Type 'Realtime' is not assignable to type 'RealtimePromise'` then it can be fixed by using `Realtime.Promise` in place of `Realtime`. I'll get the docs updated, thanks for making us aware of this 👍

**Comment by scottned** [comment]
That was it and your suggestion fixed it.  Thanks for being so responsive!

**Comment by VeskeR** [comment]
Closing this as issue has been resolved, and ably-js v2 project version fully supports and can be built using Node 18+
