### ISSUE TITLE
Switching networks reactiveness

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#155]
When running a manual test of changing networks whilst connected to Ably with a WebSocket (in Chrome), I notice two things:
- It takes a very long time for `ably-js` to detect that the existing socket connection is no longer there
- It can get stuck completely and never detect the connection is in fact gone, see screenshot below showing that the websocket transport is stuck in the pending state, yet `ably-js` according to the log thinks it is connected still

![voila_capture 2015-11-05_12-37-51_p m](https://cloud.githubusercontent.com/assets/43789/10968573/29fef918-83ba-11e5-9757-fe4743d2e1c5.png)

![voila_capture 2015-11-05_12-38-42_p m](https://cloud.githubusercontent.com/assets/43789/10968578/319505fa-83ba-11e5-97e7-75632775b7f7.png)

**Comment by SimonWoolf** [comment]
If the underlying TCP connection hasn't closed, and the browser hasn't emitted an `offline` event, then I'm not sure we have any way of detecting that we no longer have a connection other than a lack of heartbeat every 15s. 

Previous discussion at #99

Should we consider either client-initiated heartbeats or having the client go to the `disconnected` state if >20 seconds go by without seeing a server heartbeat?

**Comment by mattheworiordan** [comment]
Not sure to be honest, @paddybyers what do you think?  Should the heartbeat perhaps be based on the disconnect retry timeout, and if the client library does not see the heart beat in that time, as @SimonWoolf says, we enter the disconnected state?

**Comment by paddybyers** [comment]
I think that if we are changing things then heartbeats should originate from the client. Either way we have to have a timer running on the client, and if we're going to do that then the client may as well send them. It allows the client in future to decide the frequency, and explicitly go into a lower power state in-between, because it knows when the heartbeats will happen.

The responsibility will be on the transport rather than the connection manager, and then the transport can clean itself up and indicate its state if it goes wrong. Again it simplifies things if in future we want to allow each transport to have a different frequency.

**Comment by mattheworiordan** [comment]
@paddybyers Ok, makes sense, I will tag this issue as an enhancement we can review in 0.9 then

**Comment by SimonWoolf** [comment]
I just had this issue: my internet connection dropped for a few minutes. Browser didn't notice so didn't emit an `offline` event. Took seven minutes for the TCP connection the websocket was on to close, during which ably-js had no idea there was anything wrong (since there was an apparently connected websocket, though it wasn't getting any messages including heartbeats).

@mattheworiordan @paddybyers We said we were putting this off to 0.9, so now's probably the time to consider it. 

Reminder of the two main possibilities:

1. Have the client lib transport monitor the time since the last heartbeat, and assume the connection's down if it's been too long. (Possibly the server should send the heartbeat frequency in the connectionDetails).
2. Change the heartbeats to originate from the client, and have realtime reply (so realtime will not send non-reply heartbeats to v=0.9 clients). Probably also adding a uuid to each per https://github.com/ably/wiki/issues/24.

See also: https://github.com/ably/ably-js/issues/99, https://github.com/ably/wiki/issues/24

**Comment by mattheworiordan** [comment]
Seems sensible to think about, although not entirely convinced it's that important as TCP/IP does a reasonably decent job at detecting dropped connections most of the time.  It would be nice to improve this though so if we can come up with a simple solution then let's do it.

**Comment by SimonWoolf** [comment]
> not entirely convinced it's that important as TCP/IP does a reasonably decent job at detecting dropped connections most of the time. 

Before a few hours ago (when I got one that took seven minutes to recognise) I'd have agreed with you :/

I don't think either of those two possibilities is that complicated. A basic implementation of option 1 (websocket-only 25 second heartbeat timer) could be done in 5 minutes and needs no realtime changes. (But @paddybyers was leaning towards option 2 before, so don't want to go ahead and do that before he's weighed in)

**Comment by paddybyers** [comment]
Since we last discussed it, we have added realtime-initiated pings (to detect the transport dropping, because we had an issue with it not being detected by ELB or something). So to switch now to option 2 would involve more pain.

The argument for option 2 was that the client could determine the heartbeat frequency and so optimise for the network it was on, or the battery conditions, or whatever. Perhaps we can still do this if we do option 1, but:
- pass any non-default heartbeat interval to the client in `ConnectionDetails`;
- allow the client to request a non-default interval via transport params.

If we think those are viable ways to address that requirement in the future, I'd be ok with doing option 1 now.

**Comment by mattheworiordan** [comment]
> Since we last discussed it, we have added realtime-initiated pings

I assume you mean WS pings as opposed to Ably Realtime protocol pings?

**Comment by paddybyers** [comment]
> I assume you mean WS pings as opposed to Ably Realtime protocol pings?

yes

**Comment by SimonWoolf** [comment]
SGTM. Added https://github.com/ably/docs/pull/130.

**Comment by SimonWoolf** [comment]
Fixed by clientside heartbeat monitoring timeouts
