### ISSUE TITLE
requestToken sending key?

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-js#157]
I saw this in a snippet from Rafael:

````
ably.js:4094 Ably: Auth.requestToken(): using token auth with client-side signing
ably.js:4094 Ably: Auth.getTokenRequest(): generated signed request
ably.js:4094 Ably: Auth.requestToken().requestToken: Sending POST; function (host) { return rest.baseUri(host) + '/keys/' + keyName + '/requestToken';}; Token params: {"keyName":"79Lwsg.OXy-3g","key":"79Lwsg.OXy-3g:xxxxxxxxxxxxxxxxxxxx","capability":"","timestamp":1447238454943,"nonce":"5867553278803825","mac":"cUzoCUVivQhStfAdzGcrgFmiGrfceV/XTLUFudOXQ+0="}
````

I was surprised to see the full `key` in the request body (edited out above).

@SimonWoolf: could you have a quick look please?

**Comment by SimonWoolf** [comment]
@paddybyers I'm fairly sure requestToken isn't adding a key - I've never seen it do that, and can't see anything in the code which would do that.

It will however pass on any tokenParams you call it with (it doesn't check their validity). So presumably somewhere it's being called as `requestToken({key: key}, function(err, response) {...})` (possibly due to not being changed after https://github.com/ably/ably-js/issues/137). D'you know where the calling code is?

**Comment by paddybyers** [comment]
@SimonWoolf thanks
