### ISSUE TITLE
Wrong type return in useChannel()

### ISSUE THREAD

**Issue by phungvansyhb** [ably/ably-js#1591]
![Screenshot 2024-01-23 161448](https://github.com/ably/ably-js/assets/54164578/6955fa75-6949-4cda-99d6-a4770e7a01f2)

Enviroment : nextjs , vscode

`const {channel} = useChannel(TOPIC.GAME_ROOM.CREATE);` 
return channel has type **Types.RealtimeChannelPromise** which difference with **Ably.Types.RealtimeChannelPromise**. 
And can't get code suggestion.

**Comment by VeskeR** [comment]
Hello @phungvansyhb !

I couldn't manage to reproduce your issue on a bare bone Next.js app while using latest ably package version. It seems like the issue you're describing was fixed in [v1.2.48](https://github.com/ably/ably-js/releases/tag/1.2.48) release, in https://github.com/ably/ably-js/pull/1509.

Could you please check if you're using the latest `ably` version available?

**Comment by phungvansyhb** [comment]
@VeskeR I am sorry, I start with code base in gitHub. That's ok when I reinstall the latest version.

**Comment by VeskeR** [comment]
@phungvansyhb No worries, glad I could help and it's working now!
Closing as resolved.
