### ISSUE TITLE
Http fallback sequence tweaks

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#165]
See https://github.com/ably/ably-js/issues/160.

@paddybyers's thoughts:
> In the worst case we should have a 2-step fallback (ie best-available http transport -> jsonp). Trying all the options is bad I think, but I would prefer that we pick one and it works.

**Comment by mattheworiordan** [comment]
Notes from our discussion on this issue:

The process for the `ably-js` library should be:

* Filter transports available 
* Try the preferred HTTP transport (XHR-streaming / iFrame for one edge case)
* If that fails to connect
  * If internet up try other hosts
  * If internet not up (using same transport to determine this) try fallback JSONP transport 
* Once connected, try and upgrade to WebSockets

The 15s disconnect timeout should only apply once all the fallbacks have been exhausted, currently it seems that if the request times out in 15s, no fallbacks are used because the realtime state timeout had passed.

**Comment by SimonWoolf** [comment]
> The 15s disconnect timeout should only apply once all the fallbacks have been exhausted, currently it seems that if the request times out in 15s, no fallbacks are used because the realtime state timeout had passed.

Not sure about this part. This would mean that `realtimeRequestTimeout` no longer applies to establishing a connection, so there would be no enforced cap on the amount of time the client lib can be in the `connecting` state. (So eg any transport bug which results in it stalling while trying to connect and never actually failing, like https://github.com/ably/ably-js/issues/160, would jam things forever)

(Note: this is all separate from the `disconnectRetryTimeout`, which only starts once the client enters the `disconnected` state)

Possibly we could separate `realtimeOpenTimeout` back out from `realtimeRequestTimeout` and make it longer (maybe 30s), then have a shorter timeout for each transport connect attempt?

(Long-term, @mattheworiordan suggests we'll want to have multiple transports connecting at once (possibly staggered), choosing the first one that succeeds, to avoid a 15s wait if eg you're on a connection where the xhr attempt times out (eg https://github.com/ably/realtime/issues/371) but eg websockets or jsonp would succeed immediately)

**Comment by mattheworiordan** [comment]
@SimonWoolf I would agree that we simply separate out, and in the case of JS which has more than one transport (other client libs don't offer this currently), we simply change the default timeouts.  I would personally opt for 10s per requrest and 20s total connection timeout

**Comment by paddybyers** [comment]
I think in practice if it's going to succeed it will do so in much less than 10s. Maybe 5 isn't enough but it could be 7.5.

However, all of this is really missing the point I think. If a platform is modern enough to have XHR with CORS, which we can determine statically, then it is surely able to give us state change indications that tell us whether it has connected or not. I think our failure in the iOS case was to fail to spot that the connection had been established while we were still waiting for a connected event.

**Comment by mattheworiordan** [comment]
>  I think our failure in the iOS case was to fail to spot that the connection had been established while we were still waiting for a connected event.

Yes, that was the issue in **this case**, however it's quite plausible that in other cases, the timeout means no other transport will ever be used, which is certainly flawed.

**Comment by paddybyers** [comment]
> the timeout means no other transport will ever be used, which is certainly flawed.

Of course. My point was that we should be able to rely on detecting failure relatively quickly; in this case we would have detected failure immediately. So we need to change that timeout as discussed, but also make it so that the transport detects a problem itself by noticing that there is no connect response despite having established the connection.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/issues/279
