### ISSUE TITLE
Test client library with explicit binary protocol in JSBin

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#18]
Previously we had issues with websocket binary payloads so we need to test that this is no longer an issue

**Comment by SimonWoolf** [comment]
@mattheworiordan do you remember any particular jsbins had problems?

**Comment by mattheworiordan** [comment]
Nope, can't remember, I just know that for a period we had to explicitly disable the binary protocol in the browser because it was failing frequently.

**Comment by paddybyers** [comment]
@SimonWoolf: can you try something explicitly in jsbin (binary, force both websocket and non-websocket transports) ?

**Comment by SimonWoolf** [comment]
Tested it a bunch (using [this js-bin](https://jsbin.ably.io/uhoqoj/39/edit) on latest new-upgrade branch against dev-realtime), but couldn't see any differences between `useBinaryProtocol` true or false, on any transport, with various setting combinations.

(Did find one behaviour difference between jsbin and normal: with jsbin you get an exception if you use web_socket transport with tls:false and useTokenAuth: true. But unrelated to this so filing a new bug for it).

(don't think there's any difference with current prod either, but had difficulty consistently getting a successful connection anyway due to various other errors (see [slack](https://ably-real-time.slack.com/archives/internal/p1442320777000083)), so hard to be certain)

Closing this until we see this issue again.
