### ISSUE TITLE
usePresence fails when using AblyProvider with custom ablyId due to ablyId not being passed to useConnectionStateListener

### ISSUE THREAD

**Issue by bastiankistner** [ably/ably-js#1820]
I've just begun reworking my ably integration. I was using a single client for my multi-tenant application and different permission sets per tenant. I though it might be less error prone keeping the client alive while instantiating a new one.

But I already failed when trying to call the `usePresence` hook, which tries to setup a connection listener here: https://github.com/ably/ably-js/blob/f606332c326c3f15c12e2d6c401d1300a655e0a9/src/platform/react-hooks/src/hooks/usePresence.ts#L49

However, when using an `AblyProvider` with a custom `ablyId`, the `usePresence` hook errors because it tries to look for a `default` ablyId client.

Other hooks seem to work, but this one will never succeed with a custom client because the `useConnectionListener` is not being passed the ablyId as second argument.

Instead of 
```typescript
useConnectionStateListener((stateChange) => {
    setConnectionState(stateChange.current);
  });
```

it should be 
```typescript
useConnectionStateListener((stateChange) => {
    setConnectionState(stateChange.current);
  }, params.ablyId);
```

See https://github.com/ably/ably-js/blob/f606332c326c3f15c12e2d6c401d1300a655e0a9/src/platform/react-hooks/src/hooks/useConnectionStateListener.ts#L17

How fast could you get a fix out? Otherwise, I'll try to patch it locally.

Is using multiple clients a common use case? I wonder why no one else has yet discovered this since it should error immediately.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4890) by [Unito](https://www.unito.io)

**Comment by ttypic** [comment]
Hey @bastiankistner,

Thank you very much for reporting this, we'll release patch asap

**Comment by ttypic** [comment]
@bastiankistner,

The fix for this issue was released in version 2.3.1. If the problem persists, please feel free to reopen the issue.

**Comment by dotdev-dionne-chelini** [comment]
Hey @ttypic, I have been facing an issue with connecting Ably.Realtime which only began a few days ago. Previously, the connection was not having any issues. However since a few days ago I have been getting the following error. `Expected TextEncoder to be configured` I have bumped versions and tried the following to no prevail. 

Bumped Ably versions
Changed node environments on local
Tried using Ably/modular package
Reached out to Shopify through slack
Verified the notifications are coming through by other means. 
I still did change the API_KEY  to another Ably Channel but still get the same error.
Removed all packages - reinstalled
Removed complied packages
Rolled back to a previous branch to make sure there wasn't a accidental change
Tried turning the API_KEY into a buffer
Tried using a string literal with API KEY
Looked through Ably package.
Searched threads.....

I am currently connecting the ably client in a shared web worker. This was working really good previously. Has their been any changes that could be causing the issue. Would appreciate some input. Thanks. 


![Screenshot 2024-09-03 at 12 00 31 pm](https://github.com/user-attachments/assets/7cf72141-9fd5-4cb5-81b6-208dbcecde01)
 

<img width="1056" alt="Screenshot 2024-09-03 at 11 59 36 am" src="https://github.com/user-attachments/assets/2d4d3624-14ae-4c69-852c-fe9286b2844e">

**Comment by dotdev-dionne-chelini** [comment]
Hi @VeskeR, I have tried importing the lib you suggested but even that throws errors. Is there anyway I can connect to Ably without using the TextEncoder API?

**Comment by VeskeR** [comment]
Hey @dotdev-dionne-chelini 

>  I have tried importing the lib you suggested but even that throws errors

Just to clarify, do you mean that Ably realtime client _still_ throws an error, or it's now `fastestsmallesttextencoderdecoder` library which throws an error when you're trying to import it?
Also, make sure you're importing that polyfill library with `import 'fastestsmallesttextencoderdecoder'` statement **before** any importing anything from the `ably` package. Ideally import that polyfill in your root-most javascript file, as the first import statement.
If you're still experiencing the issue, could you please share a minimal reproducible example with us? Or describe the concrete steps to reproduce running Ably library in the environment you're doing it in. This would help us to resolve the issue quicker. Thank you!

> Is there anyway I can connect to Ably without using the TextEncoder API?
For ably-js v2 as it currently stands, unfortunately, no, TextEncoder API must be available one way or another. You could theoretically downgrade to ably-js v1 which has crypto-js lib bundled in for cases when TextEncoder API is not available, but I assume this would be a pretty big undertaking and an undesirable downgrade, so I hope it doesn't come to that.
