### ISSUE TITLE
Browser and node treat string key cipherParam differently

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#238]
So one thing I noticed while doing https://github.com/ably/ably-js/pull/236 is that nodejs and the browser treat a string `key` param differently.

[The browser feeds it](https://github.com/ably/ably-js/blob/e4363ba9ab6073c85a0a0047b0426b7e2171927f/browser/lib/util/crypto.js#L138-L139) to `CryptoJS.enc.Hex.parse(key)`, which parses it as a hex string, so one byte per two characters (and just returns nonsense if fed something outside 0-F).

Wheras [node](https://github.com/ably/ably-js/blob/e4363ba9ab6073c85a0a0047b0426b7e2171927f/nodejs/lib/util/crypto.js) just feeds it straight to `crypto.createCipheriv`, which treats it as a raw binary string -- one byte per ASCII character.

This isn't caught by the crypto fixtures as they have keys that are explicitly base64 encoded, and the tests explicitly base-64-decode them :/

Which way is right? What do the other client libs do when fed a string as a key -- interpret it as hex, or as raw bytes? The spec doesn't help much ("key string / byte array"). Ably-ruby does it the node way (`key.unpack('b*')`, #unpack treats the string as raw binary), so I'm guessing that's the one Matt prefers.

@mattheworiordan @paddybyers

**Comment by mattheworiordan** [comment]
I don't think we have specified anywhere that we expect it to be hex, so I am pretty sure the browser way is wrong. @paddybyers?

**Comment by paddybyers** [comment]
If it's an arbitrary binary array of 16/32 bytes then it can't be a raw string - it needs to be hex or base64 encoded and a string, or a buffer.

A buffer/byte array would be the natural thing provided that the language supports that, so that should be our preferred and portable API.

In the node case then we can obviously support a buffer. In the browser case then we can't - but we support WordArray so I guess it should support that.

The next question is whether or not we also support the option of passing a string, in which case we say that it is either hex or base64; hex is probably more appropriate in this case.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/240 per https://github.com/ably/docs/pull/89
