### ISSUE TITLE
Attach / reattach presence SYNC issue

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#284]
See https://jsbin.ably.io/amisux/3/edit.  Before running this test I set up two users present on the channel `test:presence`.

The first attach works fine, however the second attach seems to ignore the presence `SYNC` and never emit the `present` members on the channel.  Looking in the frames of the WS connection, here is what is sent from the point of the channel being attached.

```
{"action":12,"channel":"test:presence"}	
{"action":13,"channel":"test:presence"}	
{"action":10,"channel":"test:presence"}	
{"action":11,"flags":1,"channel":"test:presence","channelSerial":"1089494447889800:1","connectionSerial":1}
{"action":16,"channel":"test:presence","presence":[{"id":"-I73K0Dn0c-0:0","clientId":"mike","connectionId":"-I73K0Dn0c","timestamp":1465761561118,"action":1},{"id":"MirNPNo8Vz-0:0","clientId":"john","connectionId":"MirNPNo8Vz","timestamp":1465761553970,"action":1}]}
```

@SimonWoolf as this is quite likely to effect customers who reattach following connections going into the suspended state, I think we should try and implement a fix ASAP.

**Note to self!**

Once this issue is resolved I need to delete that API key as I set it up as temporary one!

**Comment by SimonWoolf** [comment]
@mattheworiordan FWIW the current behaviour looks like a deliberate design decision. On detach, the presence map is not discarded; instead it's kept, and then on reattach + sync, only new members who weren't there last time are emitted.

It isn't obvious to me that the current behaviour is wrong. But equally, happy to change it so that the members map is discarded on detach if you think that'd be more intuitive behaviour. If so, we should also modify RTP5a: currently it says "(RTP5a) If the channel enters the DETACHED or FAILED state then all queued presence messages will fail immediately" - if we're requiring members map to be discarded on detach this should be explicit.

**Comment by paddybyers** [comment]
If you're detached then the presence map will become stale and I can't really see a use-case for retaining it. You' still need to send the same number of messages to re-sync it. You stand a chance of getting valid data from it if you do `waitForSync: false` but TBH I don't really see that as valuable.

**Comment by mattheworiordan** [comment]
@SimonWoolf I agree we should modify the spec if we want to be explicit.

To avoid ambiguity, I think we should discard it in all cases, and when reattaching all presence events should be emitted as presence sync occurs.  Should we add a specific note in our spec for that use case too i.e. mention that members should be discarded, and on re-attach, there should be a test to ensure presence is resynced?

**Comment by SimonWoolf** [comment]
> To avoid ambiguity, I think we should discard it in all cases, and when reattaching all presence events should be emitted as presence sync occurs. 

Done in https://github.com/ably/ably-js/issues/287
