### ISSUE TITLE
Quick detach never detaches

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#285]
See https://github.com/ably/ably-js/issues/284, I had to place a timeout in the test as without a timeout the channel never became detached.

See https://jsbin.ably.io/amisux/4/edit

Note how the channel never becomes detached, and there are Comet request errors.  I assume this issue has something to do with the DETACH being sent during upgrade?

**Comment by SimonWoolf** [comment]
@mattheworiordan probably, though in theory, activating the upgrade transport is supposed to be postponed until attaches and detaches are complete (the `nopending` mechanism). Unfortunately I can't replicate the problem from here (even forcing ably-0.8.19.js to avoid the new preferredTransport stuff). Could you post a complete console log of it happening?

**Comment by mattheworiordan** [comment]
I can't replicate this either n ow :(

**Comment by SimonWoolf** [comment]
Ah well. If it happens again, reopen with a log.

**Comment by SimonWoolf** [comment]
Reopening - I managed to reproduce this. The bug occurs when the presence set is nonempty, so there is a presence sync that overlaps with the detach. The `nopending` mechanism is effectively just a boolean lock per channel, so when the presence sync finishes it unlocks the lock, even though the detach hasn't finished.

(Fixing https://github.com/ably/realtime/issues/522#issuecomment-225596458 will probably require major changes to the `nopending` stuff anyway, so I'll roll the fix for this into whatever we decide on there)

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/292
