### ISSUE TITLE
Long-lived upgrades

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#299]
I was just thinking that users who are using the Node version of the library server-side would probably in almost all cases not want to be stuck on a Comet transport.  As such, if somehow following a failure the client used Comet, should it not try and upgrade periodically again anyway?

**Comment by SimonWoolf** [comment]
We could do, but - do we have any evidence that this is a problem that exists? Network conditions that allow comet requests but block websocket ones tend to be permanent (proxies or whatever), no?

(And in the event of a soft upgrade failure (unable to recover connection etc) the client as currently configured will complete the upgrade anyway and take the continuity loss hit, it won't stick with comet)

**Comment by mattheworiordan** [comment]
>  do we have any evidence that this is a problem that exists?

We do now 😄

**Comment by SimonWoolf** [comment]
> We do now :smile:

Tbh I'm not sure we do though :). Post-#302, if an upgrade sync fails, the library doesn't just keep on using the same comet transport forever (since it doesn't know if realtime got the sync or not, so the transport might have been disposed). It starts from scratch, with a new comet transport, and a new websocket upgrade attempt. It'll only stick with comet if the websocket attempt doesn't connect at all, or is closed with `wserror` before it connects. (It isn't even timed -- since the lib is happily `connected` and working with comet, the websocket has as long as it likes to connect). Under those circumstances, is there any chance that subsequent websocket connections might still succeed?

**Comment by mattheworiordan** [comment]
Fair enough... I will close this and reopen if we hear from customers this is a problem
