### ISSUE TITLE
Unable to recover connection - causes connection to be closed / failed?

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#329]
A customer has reported seeing the following in the console:

```
bly: ConnectionManager.activateTransport(): error = [c: Unable to recover connection: not found (XiV8Rmqv83DhESmO); statusCode=400; code=80008] 
ably.min.js:84 Ably: Request.onabort(): Request aborted due to request timeout expiring (event type: abort) 
ably.min.js:84 Ably: CometTransport.sendItems(): on complete: err = {"message":"Request aborted due to request timeout expiring (event type: abort)","code":80000,"statusCode":408} 
rest.ably.io/comet/e9169444!FRCOf1MN8FfBoEcg-60bdfe9169444/send?access_toke…k3h1HBVt2iwIKMpiMRCrM11dD5NimcAl9KgNoSTDOEymA-sPaSo&rnd=6640857852998276:1 POSThttps://rest.ably.io/comet/e9169444!FRCOf1MN8FfBoEcg-60bdfe9169444/send?acc…kDk3h1HBVt2iwIKMpiMRCrM11dD5NimcAl9KgNoSTDOEymA-sPaSo&rnd=6640857852998276 404 (Not Found) 
ably.min.js:84 Ably: CometTransport.sendItems(): on complete: err = {"statusCode":404,"code":80016,"message":"Invalid transport id: 60bdfe9169444","serverId":"frontend.86b0.1.eu-central-1-A.i-6eba06d3"}
```

Following that, they report that the connection remains inactive.

@SimonWoolf we need to investigate if this is a JS issue or not?

**Comment by SimonWoolf** [comment]
Unfortunately there isn't enough here to investigate. (Error-only) log shows:
- Realtime failed to recover connection state (probably it just expired). Normal behaviour
- At some later point, a comet request timed out. not normal/expected, but stuff happens, sometimes things time out
- At some later point, realtime responded to a comet request with an 'Invalid transport id'. That happens when the client tries to use a transport that realtime's just disposed of, usually because of a token expiry. annoying, but sometimes expected behaviour, and shouldn't cause any problems now that we've [made it nonfatal to the connection](https://github.com/ably/realtime/pull/597/commits/1e23571b2ae2940e9fe6374243d7602f1c83ad75).

Customer said they reattached to the channel and connection was connected, but pub-sub still wasn't working. If that's true then of course we have a serious issue, but there's nothing in those three lines that would help tell whether it is or not, let alone debug anything.
