### ISSUE TITLE
closeOnUnload does not work in IE11

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#338]
See internal support ticket 1321 for reference.

> closeOnUnload option passed to the Ably.Realtime client doesn't seem to work on Internet Explorer. I'm pretty sure adding a return with undefined/null value in the beforeunload event handler should do the trick.

> I'm experiencing this issue on IE 11. You can reproduce this with a basic scenario - create a Ably's Realtime instance with closeOnUnload option enabled. Enter presence on a channel, close the browser, the other client won't receive a leave message until the connection times out.

@SimonWoolf mind taking a quick look?

**Comment by SimonWoolf** [comment]
> I'm pretty sure adding a return with undefined/null value in the beforeunload event handler should do the trick.

Returning a value from the beforeunload handler is for showing an 'are you sure you want to close this page' dialogue to the user, which we don't want to do.

The issue seems to be that IE is way stricter that Firefox or Chrome in how much time we have after the beforeunload handler returns before the page closes (I guess it assumes that everything you want do in the beforeunload handler is synchronous), to the extent that doing the `closeImpl` in a `nextTick` callback was enough to make it not run.

Removing the nextTick (as it's not actually needed) seems to fix it... mostly. If using comet, it sometimes doesn't have time to actually do the xhr request (which is async) properly before the page closes. Can make it work completely reliably by forcing a busyloop for a few milliseconds before the beforeunload handler returns, but that's ridiculous. Given IE11 supports websockets, I think this fix is sufficient.

Fixed by https://github.com/ably/ably-js/commit/70bce3d370994ce834ac281bd88fd26fd7bf3af9
