### ISSUE TITLE
Document supported platforms in the README file

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-js#457]
- [x]  add section to the README that says which platforms we support
- [x] Add node 4.2, 6.13, 8.9.4, latest stable
- [x] Add browsers IE8, 9, 10, 11, 16, Chrome, Firefox, Safari 11 on iOS, Safari 11 on macOS, Chrome Android 6

**Comment by funkyboy** [comment]
@paddybyers @mattheworiordan need your help on the TBD ^

**Comment by paddybyers** [comment]
When this was first implemented, we intended to support all desktop browsers with the exception of IE6 and earlier, and all versions of iOS Safari and Android's browser. I think we officially stopped supporting IE7 (which I think was the only browser that didn't support JSON natively). We also officially stopped supporting some transports (iframe and flash websockets) - but this didn't stop any browsers from working; it only meant that certain browsers would fall back to JSONP.

@SimonWoolf has done most of the cross-browser work and fixed multiple issues over the years but I wasn't aware of specific problems that would cause any of the "supported" browsers (ie IE8+, Safari, Chrome, Firefox, Opera, Android) to fail.

Then we have unsupported features. For example, we use local storage to persist connection state for `recover` mode; not all browsers support that, but it just means that for some browsers either `recover` isn't supported, or the site would need to implement something itself.

So then the question is which ones do we test - and if we find problems, how much effort do we put into fixing them? If a browser (eg IE8) shows a large number of test failures, and we think the IE8 population is too small to worry about, then we can list IE8 as unsupported. Otherwise, we could document known issues for certain browsers if those issues affect only certain use-cases (eg "crypto is unsupported on IE8").

So TBH I think to advertise a formal supported browsers list we need more concrete data so we know where the issues are, and we can decide which are worth fixing.

**Comment by funkyboy** [comment]
@paddybyers Cool. Let's resume this when I finish #452

**Comment by funkyboy** [comment]
As per call today with @paddybyers we'll document supported platforms in the README file.
In the case of `js` we'll list node versions (LTS + latest) and browsers.

**Comment by SimonWoolf** [comment]
@funkyboy don't forget to update the `engines` field in package.json

**Comment by funkyboy** [comment]
Resolved in https://github.com/ably/ably-js/pull/498
