### ISSUE TITLE
Some test failures with old versions of IE exposed by switch to browserstack

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#486]
- [x] [request_batch_api_partial_success_binary](https://travis-ci.org/ably/ably-js/jobs/358320054#L2332) - [Related PR](https://github.com/ably/ably-js/pull/495)
- [x] auth_expired_token_string_* - [Related branch](https://github.com/ably/ably-js/tree/fix-failing-tests-on-IE11-ci)
- [x] publishQueued_* - [Related PR](https://github.com/ably/ably-js/issues/450#issuecomment-377317037)
- [x] presence_sync_interruptus - [Related Branch](https://github.com/ably/ably-js/tree/fix-presence-sync-test-ci)

**Comment by funkyboy** [comment]
Update about `auth_expired_token_string_ *` tests

Up to this commit https://github.com/ably/ably-js/commit/f26d7a96f0a017b27bb6194506149e9a550fcdfb tests on this branch https://github.com/ably/ably-js/commits/fix-failing-tests-on-IE11-ci pass locally (tested multiple times) but fail on BrowserStack https://travis-ci.org/ably/ably-js/builds/364090419

When they do fail it's due to an issue on the BrowserStack end. Their "machine" seems to be running out of memory. Hence, after a while, batches of tests fail until a tear down operation "cleans the context". I am in touch with their support team about this and we have a meeting scheduled.

**Comment by funkyboy** [comment]
Update about `presence_sync_interruptus`

### Description

Used to fail [at this point](https://github.com/ably/ably-js/blob/fix-presence-sync-test-ci/spec/realtime/sync.test.js#L526). Error was "attach timed out", for [this attach operation](https://github.com/ably/ably-js/blob/fix-presence-sync-test-ci/spec/realtime/sync.test.js#L516). 
Reason was that the channel (and not the connection) was in a `suspended` state, which I detected using [this log statement](https://github.com/ably/ably-js/blob/fix-presence-sync-test-ci/spec/realtime/sync.test.js#L513).

I can't reproduce it anymore. But yesterday I was able to collect logs of successes and failures, both on IE11 and Chrome 65. Attached for future reference.

[log-chrome-success.txt](https://github.com/ably/ably-js/files/1899654/log-chrome-success.txt)
[log-chrome-fail.txt](https://github.com/ably/ably-js/files/1899655/log-chrome-fail.txt)
[IE11-fail.txt](https://github.com/ably/ably-js/files/1899656/IE11-fail.txt)
[IE11-success.txt](https://github.com/ably/ably-js/files/1899657/IE11-success.txt)

**Comment by SimonWoolf** [comment]
All these issues have since been fixed
