### ISSUE TITLE
Usage with Heroku multiple dynos

### ISSUE THREAD

**Issue by monossido** [ably/ably-js#488]
Hello.
I'm using Ably with nodejs in a server with two professional dynos.
Unfortunally I started some limited production "test" with an API key generated throught the official website, I'm not using the ably heroku addon.

With two instance of nodejs I can see two presence in my channel, the listener is calling twice and server send one "responding" message two times... 

I suppose that with ably addon this stuff are handled by the addon itself...can I do something before migrate to the addon?

Thank you.

**Comment by SimonWoolf** [comment]
Hi @monossido . Nah, the heroku ably addon doesn't do anything special for that, api keys generated through the heroku addon don't behave any differently from ones generated through the website.

So you have some things you want your server to do in response to realtime actions by the client, but you have two servers and you only want one of them to do those things, right? A few options:

- Handle realtime actions from a server with only one dyno

- Instead of having your servers respond to messages received over a channel, use [our Reactor Queues](https://www.ably.io/documentation/general/queues): add a rule to send all messages that need a server response to a queue and have your servers all consume from that. The queue model is to [deliver a message only to one of the consumers](https://blog.ably.io/message-queues-the-right-way-to-process-and-work-with-realtime-data-on-your-servers-2d15985301f8) (as opposed to the pub-sub model, which delivers to all subscribers), so then only the server that consumes it will handle it. (Note that this will add a few hundred milliseconds of latency over pub-sub).

- Have each request only be handled by one server based on a hash of some property of the request. E.g. you could have servers all enter a presence channel. When any server enters or leaves, each server lists present members ordered by their connectionIds, giving each one an index (e.g. so 'afoobar' -> 0, 'zbazbaz' -> 1). When a message comes in over Ably that a server needs to respond to, take its connection ID, reduce to a number, calculate that modulo the number of servers, and then have only the server with the corresponding index will respond to it.

- Have the servers pick a leader amongst themselves, who's responsible for handling Ably actions. For example, you could unconditionally connect to ably and attach to a channel that only your servers can access, then enter presence on that channel if and only if there are not yet any present members. Then only one of your servers will be present on that channel; that one is be the leader. The other would subscribe to presence, and enter it and become the leader if and when the first leaves presence (e.g. due to its dyno recycling). As described that would be a bit vulnerable to race conditions if both enter presence at the same time, and won't scale well with increasing numbers of servers. You could patch around that with random backoff. The better / more general solution would be a [leader election algorithm](https://en.wikipedia.org/wiki/Leader_election), such as Raft, which you could implement using Ably as a message bus. But this is starting to get a bit sledgehammer-to-crack-a-nut :slightly_smiling_face:

(btw, don't worry about it for this time, but if you have any queries in future that aren't bugs in ably-js, please send them to support@ably.io rather than filing a github issue)

**Comment by monossido** [comment]
Thank you very much for the informations.
I've just implemented something similar to solution 3 and it works. But I will check solution 1.

Sorry if it was not the right place.
