### ISSUE TITLE
Create TS sample project

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-js#500]
- [x] Create TS sample project
- [ ] Move project [under Ably](https://github.com/ably) when approved
- [ ] Add link to it in the README file

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-300) by [Unito](https://www.unito.io/learn-more)

**Comment by funkyboy** [comment]
@paddybyers @mattheworiordan Sample TS project here: https://github.com/funkyboy/ts
When you approve I'll move it under [the Ably organization](https://github.com/ably/)

**Comment by mattheworiordan** [comment]
Why does your TypeScript demo use Javascript?

**Comment by funkyboy** [comment]
@mattheworiordan honestly, really honestly, I didn't want to deal with webpack :)
Anyway, new version of the project here: https://github.com/funkyboy/ts. JavaScript-free.

**Comment by mattheworiordan** [comment]
I think this example needs to show better coding practices as well as show good practice for Ably.

* The name "Ably JS" in the readme does not make sense for someone who does not know what Ably JS is.  This is an "Ably Javascript client library SDK"
* Why not put the API key in a shared require for ClientOptions?  That way we don't have to ask someone to add their key in two places?
* Why are your referring to `./console/index.ts` when that could be friendlier as `[consule/index.ts](./console/index.ts)`. Same applies to all files.
* Why are you calling `./node_modules/.bin/tsc`?  Why not instruct people to install `ts-node` (`npm install -g ts-node`) and then instead of `./node_modules/.bin/tsc ./console/index.ts && node ./console/index.js` it could simply be `ts-node console/index.ts`.  I personally think that's easier to read in a demo.
* Why is the repo called `ts` instead of `typescript-demo` for example?
* The demo does not explain what it does, shouldn't you offer some background in the README so that the user knows what the console and webapp does with Ably?
* You are not showing handling of connection failed / disconnected states.  Given we should show best practice and it would be trivial to do, should we not do this?
* Same applies to channels.
* In some TS files you use `;` at the end of lines in other places you don't.
* Can you change "Check that the message you sent is printed in the first terminal" to be more clear what is happening i.e. "Check that the message you published from the webapp has been received in the console app via Ably running in your terminal."
* Why are you setting ` options.queryTime = false;` to false in all demos?  Wouldn't this confuse users?
* Should we not add a comment in the ClientOptions that whilst for this demo we use an API key fro simplicity, we recommend the use of token authentication in most untrusted client devices.
* You're mixing lambda style and functions, `this.client.connection.on('connected', () => {` and `this.client.connection.on('disconnected', function() {` two lines down.  The code we produce is a reflection of us as a business, and this type of inconsistency really concerns me.
* should we not include at least a simple string message in `this.chatChannel.publish(message, '');`?  Also, the first argument of a publish is the `name` field, so it this intentional to pass in the `message` var?

**Comment by owenpearson** [comment]
Closing in favour of #686
