### ISSUE TITLE
Use Proxy 

### ISSUE THREAD

**Issue by p3pp8** [ably/ably-js#536]
Hello, we need to configure AblyJS to pass through our Proxy server this, of course, for security reason and, it's mandatory for us, so, here is the question: Is there any way to instruct AblyJS to use a Proxy server? Is possible, as last resort, to patch the code to make it possible?
Any help is really really appreciated!!!

Giuseppe

**Comment by SimonWoolf** [comment]
You don't mention if browserside or nodejs-side? If browserside, you should be able to just configure your proxy in the browser settings which would allow the Ably connection to tunnel though to the Ably endpoint without any other configuration change, assuming your proxy supports HTTP CONNECT.

If serverside, there's no explicit proxy support, but you can configure the hostname and port explicitly when you instance the library, as follows:
```
new Ably.Realtime({
  restHost: <hostname>,
  realtimeHost: <hostname>,
  port: <port for non-TLS connections>,
  tlsPort: <port for TLS connections>
});
```
If your proxy doesn't support websockets, you can force comet with `transports: ['comet']` serverside (fallback transports are by default disabled on node). If you need to disable tls you can set `tls: false`.

There is one url that currently isn't configurable, which is a hard-coded 'internet-up url' that ably-js checks if it can't connect to an endpoint, to determine if the issue is client internet connectivity or a serverside issue (so to decide if it should try one of the fallback hosts). It should be possible to make it configurable through clientoptions if necessary (we can prioritise that as a feature request depending on your package).

**Comment by p3pp8** [comment]
@SimonWoolf Thanx for the answer. You're right, i had to specify it, anyway, it was ServerSide only, i've just tried your solution but unfortunately it doesn't work, i've tried this way:

`
new Ably.Realtime({
  restHost: https://myproxy-address,
  realtimeHost: https://myproxy-address,
  tlsPort: 3128,
  transports: ['comet']
});
`

But i've a 401 error with code 80019 and cause 40170. I hope this could help identifying the problem!

thanx again!

**Comment by SimonWoolf** [comment]
Per https://github.com/ably/ably-common/blob/master/protocol/errors.json#L52 , 40170 is an error from the client auth callback.

There isn't a bug in ably-js here, so if you don't mind I'm going to close this issue and direct you to https://www.ably.io/support for further support via the ticketing system.

**Comment by p3pp8** [comment]
@SimonWoolf Ok if the configuration above is correct for you, but it doesn't work for me, so i think we have to find another RT service as it is mandatory for us to use a proxy as already said. I gonna try PubNub or something else, i'll see. I hope in the future that support for proxy servers will be added to AblyJS.
Thanx anyway for the support!
