### ISSUE TITLE
Bundling with webpack including ably

### ISSUE THREAD

**Issue by mbrevda** [ably/ably-js#544]
I'm trying to bundle ably for serverless environments. While the webapck instructions recommend keeping ably external, I'd like to package my entire function as a single file (for both speed and space). It seems that in the final bundle, ably still expecting files in their proper place and webpack doesn't know to parse the `includeScript` calls and hence doesnt include those files. Is there something that I can do to bundle everything up anyway? If not, would you consider creating a server bundle (a la the browser bundle)?

Thanks!

**Comment by SimonWoolf** [comment]
Currently serverside usage is only supported as a normal node module.

Could you clarify what "speed and space" advantages you expect to get? The extra space used (from ext4 block size & file metadata) should be minimal, and I'd be surprised if any difference in loading speed from one vs several files was big enough to be measurable even in a microbenchmark, let alone real world usage.

**Comment by mbrevda** [comment]
Storage space definitely isn't as big of a deal as it was back in the 486 days. And boot time isn't much of a concern with long-running servers. In serverless environments, "cold boots" are a much larger concern. Hence, anything that can minimize disk reads and code retrieval/parsing will help minimize the cold boot time.

My goal is a single function with all the code it needs to be hoisted to where it needs to be. This greatly minimizes disk reads (no `require()`'s),  minimizes parse time (less code to parse), and minimizes execution time (via hoisting).

**Comment by SimonWoolf** [comment]
Fair enough.
Unfortunately, I don't think a serverside bundle is likely to happen (unless specially commissioned by an enteprise customer), since if we're going to put any significant amount of effort into that I'd prefer we put that effort into just [moving over to es6 modules](https://github.com/ably/ably-js/issues/477) (in which case you can just use webpack) -- we're planning on doing that at some point anyway, and that task would make all the custom bundling stuff based on the current architecture obsolete.
Thanks for the suggestion, though!

**Comment by mbrevda** [comment]
Yeah, that would work, too. I'll follow along in that issue. Do you have an ETA for es6 modules?

**Comment by FalkNisius** [comment]
Please do it fast, because the ably 1.0.18 blows up the server side node image with 61.1MB of duplicates ES6 Modules in the node_modules_es6 folder. It is more than a half of the complete image size. Thank You

**Comment by SimonWoolf** [comment]
Hi @FalkNisius . Thanks for reporting that, which was due to a bug in npm in how it parses `.gitignore` (git allows prefixes in .gitignore, so that other node_modules folder was ignored due to the `.node_modules` entry in .gitignore; npm apparently does not, so it was mistakenly including it the package).

I've just released ably-js 1.0.19 with a fix for that, reducing the package size to 1.1MB compressed, 4.3MB uncompressed.

**Comment by FalkNisius** [comment]
Thanks for fast response, image is much smaller in size
