### ISSUE TITLE
Unexpected state change during detach

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-js#552]
A call to `detach()` is returning an error:

```
{"message":"PubSub detach failed","responseJSON":{"channelId":<redacted>,"message":"Internal channel error","code":50001,"statusCode":500}}
```

This seems to be coming from https://github.com/ably/ably-js/blob/master/common/lib/client/realtimechannel.js#L189

**Comment by blamattina** [comment]
Verbose logs; [ably-detach-failed.log](https://github.com/ably/ably-js/files/2573358/ably-detach-failed.log)

**Comment by SimonWoolf** [comment]
Hi @blamattina ,

It looks like you're start off by calling detach() on that channel (line 633), and then ~10ms later you call attach() on it (line 649). This causes the detach() to call back immediately, with what is admittedly a not very helpful error (I'll improve that); a more helpful error would be something like: "Detach was cancelled because the channel was requested to be attached".

The attach then fails because the server responds to your initial detach request (with a `detached`) before getting the attach request. In the Ably protocol, the server is the source of truth for what state the channel is in: the channel becomes attached/detached when the server tells it that it's in that state. So when the next protocol message after an `attach()` the channel gets is a `detached`, the attach fails. That is, the pipelining is somewhat naive: attach and detach requests have no uniquifier other than the channel ID, so the callback called just from the first channel state protocolmessage received after requesting a state change.

A little later it gets the `attached` once the server has received and responded to the `attach` request -- line 845 -- and the channel then becomes attached, but by then the attach() callback has already been called.

(There is, I think, one place here where the library is behaving wrongly per our spec: the `detach()` should call back only once the first response has been received from the server, rather than as soon as you call `attach()`. But that change won't solve your problem)

Is your calling detach() and attach() in quick succession deliberate? If so, why?

**Comment by blamattina** [comment]
Thanks for the clarification. I figured it was something that we were doing wrong but I wasnt sure what. We should not be calling `attach()` and `detach()` is quick succession. I'll look into that. Thanks!
