### ISSUE TITLE
Would be possible clear channel remotelly?

### ISSUE THREAD

**Issue by thadeu** [ably/ably-js#626]
I would like flush/clear presence channel via Rest or Realtime remotelly, how to do?

**Comment by SimonWoolf** [comment]
Hi! Issues in this repository are for ably-js bugs only. For support, please use https://www.ably.io/support , which has FAQs and links to live-chat with us, email us, or file a support ticket.

-------

But no, you can't clear a presence channel of presence members remotely. If someone's in a presence channel, they will only leave if either they leave() explicitly, detach from the channel, or their connection is closed (or their network drops etc.). You can of course send the client a message (in that channel or otherwise) to ask them to leave, i.e. that triggers some code in your app to call leave().
