### ISSUE TITLE
IE11 syntax error with webpack

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#627]
Reported by customer , ticket 105359

> We're getting an occasional error reported to us from our bug reporting tool, Raygun.  It seems to be isolated to IE 11 on Windows 7.  This is not a big population of our users thankfully.  This is low priority but I thought the error might be helpful.  I also might need to update our Ably js client, I haven't updated in ages.  Error below:

```
Message: Syntax error
at self line 6013, column 4 (webpack:///./node_modules/ably/browser/static/ably-commonjs.js:6013)
```

```
     self.scheduleTransportActivation(error, transport, connectionKey, connectionSerial, connectionId, connectionDetails);
        }
    } else {
        self.activateTransport(error, transport, connectionKey, connectionSerial, connectionId, connectionDetails);
 
        /* allow connectImpl to start the upgrade process if needed, but allow
         * other event handlers, including activating the transport, to run first */
```

**Comment by SimonWoolf** [comment]
That snippet includes no syntax errors, and we have no idea what version of ably-js (or for that matter webpack) we'd even be trying to test this is from other than that it's an (unspecified) old version. So this is not currently investigable. Certainly don't yet have enough information to conclude the problem is an sdk bu yet, no point having parallel conversations in freshdesk and github. Will reopen if we have enough information.
