### ISSUE TITLE
json3 deprecated warning on npm install

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-js#640]
On `npm install` I'm seeing:

```
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
```

Alongside #639 it looks like this dependency is also coming in via [ably-forks/karma](https://github.com/ably-forks/karma) - acknowledging @SimonWoolf's [comment](https://github.com/ably/ably-js/issues/639#issuecomment-611624506), I still think it's worth fixing for those who may decide to do some work on this library.

```
ably@1.1.24 /Users/quintin/code/ably-js
└─┬ karma@0.13.22 (github:ably-forks/karma#4e2d5d8b0242e037a319ef33d3c2504280cde6f9)
  └─┬ socket.io@1.7.4
    └─┬ socket.io-parser@2.3.1
      └── json3@3.3.2 
```

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-308) by [Unito](https://www.unito.io/learn-more)

**Comment by venkat2594** [comment]
F:\React\webchat>npm i socket.io-chat
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm ERR! Unexpected end of JSON input while parsing near '...:3292}},"7.0.0-beta.5'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VENKAT\AppData\Roaming\npm-cache\_logs\2020-11-18T11_26_00_513Z-debug.log

**Comment by owenpearson** [comment]
Closing as this no longer occurs (probably resolved by [this commit](https://github.com/ably/ably-js/pull/892/commits/015ea9c4af443da5385dcf59cf61f399390de4f3))
