### ISSUE TITLE
bundling for serverless functions

### ISSUE THREAD

**Issue by shrugs** [ably/ably-js#643]
hi! i'm aware of issue #544 from 2018, but i'd like to re-open the discussion around serverless targets.

i'm specifically attempting to include the ably-js library within a next.js api route, which is run as an AWS lambda bundled by webpack.

the initial problem is that because the library is effectively computed at require time (using the `includeScript` within a vm context, they aren't bundled by nextjs's webpack config, resulting in an `ENOENT` when `includeScript()` occurs. the `externals` declaration won't affect this behavior, afaik.

i attempted to work around this by `preval`ing the module with https://github.com/kentcdodds/babel-plugin-preval, but was unable to get this to work correctly. the dynamic dependencies on various globals seems to make this approach a bit complicated, resulting in various errors throw during preval's babel step.

i'd love any suggestions you have. if i can figure out how to make webpack bundle all of the files within the `ably` module (instead of just the ones that are statically required), then perhaps the dynamic requirement of those files at runtime won't be an issue? likewise, if pre-evaluation is working, we could inline a runtime-dependent module on build, which would satisfy webpack's bundling logic.

**Comment by QuintinWillison** [comment]
Hello @shrugs. Could you please expand as to what you're wanting to do with Ably? It seems like #477 was spawned from #544 and is still on our backlog. I just think that if we can understand what features of Ably you're using then we might be able to suggest an alternative option for you, in the meantime. Thanks.

**Comment by SimonWoolf** [comment]
> if i can figure out how to make webpack bundle all of the files within the ably module (instead of just the ones that are statically required)

Hi @shrugs . What you have suggested is indeed the approach we recommend for using ably-js with aws lambda at the moment. You can accomplish this by adding `'ably'` to the list of `externals` in your webpack config, as described in the readme https://github.com/ably/ably-js#serverside-usage-with-webpack . Hope that helps.

BTW, if you have any queries in future that aren't new bugs in ably-js, please use our support process per https://ably.io/support rather than filing a github issue - thanks

**Comment by SimonWoolf** [comment]
> the reason i mention next.js is that because the serverless functions are exclusively bundled by webpack, afaik there's no way for me to tell next "hey also include this entire directory" in the output, which is why placing ably into externals alone isn't a solution in my case.

I am not familiar with next.js, but we have come across similar issues with other frameworks that create serverless bundles; so far every one has some way to modify the build, eg to one that executes the normal build command (with ably excluded using `externals`) and then installs ably in the right place as a normal npm package afterwards. E.g. see this support article for using ably-js with the 'shep' serverless framework: https://support.ably.io/en/support/solutions/articles/3000084368-how-do-i-use-ably-js-with-shep- . (If there's no built-in way to alter the build at all, then as a last resort you can always just change the project build script from `next build` to one that does that and then copies node_modules/ably to the right place in the build artifact directory tree).

> on option that just occurred to me is manually sending an HTTP request, rather than bundling the ably library. i'll plan on doing that, then, even though i'd prefer the resilience of ably-js. how does that sound as an alternative?

That would work, but we recommend against it, for the reasons detailed in https://support.ably.io/en/support/solutions/articles/3000061848-should-i-use-the-rest-api-directly-

**Comment by shrugs** [comment]
got it, thanks! that help article is good info. i'll keep an eye on on the es6 module rewrite

**Comment by sinn1** [comment]
Sorry to comment on a closed post, but this is my exact problem. Happy to create a new one if needed.

@shrugs did you manage to get this working?

@SimonWoolf do you know if anyone's successfully got this working with NextJS? i.e. does NextJS support the workaround suggested? I ask because I've been trying for a good few hours to externalise the node module and use 'require' as suggested with limited luck...

next.config.js
`
module.exports = {
  env: {
    ABLY_ROOT_KEY: process.env.ABLY_ROOT_KEY,
  },
  webpack: (config, options) => {
    if (!config.externals) {
      config.externals = [];
    }

    config.externals.push({
      'ably': 'ably'
    });
    return config;
  }
};
`

serverside-usage.js
`
var Ably = require('ably');
`

This works when running locally, both `npm run dev` and `npm run build && npm start`, but once deployed to Vercel (zeit), the same error keeps occurring:

`Error: ENOENT: no such file or directory, open '/var/task/node_modules/ably/nodejs/platform.js'`


Any help or pointers would be grateful. Any other workarounds are welcome too... my immediate use case is:

publishing to channel from serverless function
returning token from serverless function

**Comment by shrugs** [comment]
@sinn1 i'm still using the manual http post request, but i found the copy-webpack-plugin which you might be able to use to wholesale copy the ably node module into the correct place

https://webpack.js.org/plugins/copy-webpack-plugin/
