### ISSUE TITLE
Bad type declaration for RealtimeChannelBase.unsubscribe

### ISSUE THREAD

**Issue by jscheid** [ably/ably-js#667]
I might be missing something but calling `unsubscribe` without any arguments will cause `EventEmitter.off(undefined, undefined)` to be called, and that doesn't do anything, or is undefined behavior I guess.

I believe the first argument to `unsubscribe` should not be declared optional. The way it is now, one might get the idea that calling it without arguments will unsubscribe all listeners.

https://github.com/ably/ably-js/blob/38d9f1c40b16fd4b09770830c3d84d6e5a37c1cc/ably.d.ts#L521

**Comment by SimonWoolf** [comment]
> The way it is now, one might get the idea that calling it without arguments will unsubscribe all listeners.

I hope so, since that idea would be correct, it does exactly that 🙂

See our api documentation https://www.ably.io/documentation/realtime/channels#unsubscribe , the last overload:`unsubscribe() - Unsubscribes all listeners to messages on this channel. This removes all earlier subscriptions`. See also [the implementation of `EventEmitter.off()`](https://github.com/ably/ably-js/blob/38d9f1c40b16fd4b09770830c3d84d6e5a37c1cc/common/lib/util/eventemitter.js#L84-L90).

**Comment by jscheid** [comment]
Oh, apologies... I had only looked at https://nodejs.org/api/events.html#events_emitter_off_eventname_listener where that usage isn't documented. All good then.
