### ISSUE TITLE
present events don't trigger after calling presence.get() with promise api

### ISSUE THREAD

**Issue by akhudek** [ably/ably-js#722]
Hi, 

I'm using version 1.2.6 with typescript and the promise api. It seems that after calling presence.get(), subsequent calls to subscribe on the channel presence no longer receive 'present' events. Testing on jsbin.ably.io with the standard javascript API doesn't seem to show the same behaviour.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-666) by [Unito](https://www.unito.io/learn-more)

**Comment by owenpearson** [comment]
Hi @akhudek, thanks for reporting this issue to us. I can reproduce this issue locally and it does appears to be a bug in the library. I'll look in to this and let you know in this issue when I have a solution.

For visibility, here is a minimal working example to reproduce the behaviour. We expect to see a `present` even for client3 but it doesn't fire, however the event does fire if you comment out the call to `presence.get()`. 
```js
const Ably = require("ably");

const key = "my_api_key";
const channelName = "test_channel";

(async () => {
  const client1 = new Ably.Realtime.Promise({ key, clientId: "client1" });
  const client2 = new Ably.Realtime.Promise({ key, clientId: "client2" });
  const client3 = new Ably.Realtime.Promise({ key, clientId: "client3" });

  const channel1 = client1.channels.get(channelName);
  const channel2 = client2.channels.get(channelName);
  const channel3 = client3.channels.get(channelName);

  await channel2.presence.enter();

  const initialPresence = await channel1.presence.get();
  console.log(initialPresence.map((msg) => msg.clientId));

  await channel3.presence.enter();
  
  // set timeout to ensure that listener is attached after client3 has entered.
  setTimeout(() => {
    channel1.presence.subscribe((msg) => {
      console.log(msg.action, msg.clientId);
    });
  }, 2000);
})();

```

**Comment by owenpearson** [comment]
@akhudek I've looked in to this and have found that this is actually expected behaviour: `present` events only fire when the client attaches to the channel for the first time. The reason you don't see any `present` events after calliing `presence.get` is that this method implicitly attaches the client to the channel, for simplicity. You can demonstrate this by replacing the call to `channel.presence.get` with a call to `channel.attach` (or any other method that implicitly attaches to the channel) and you'll still not see any `present` events.

If you want to get a list of every client present in the channel at a given time you should use `presence.get`. I hope this helps, thanks.
