### ISSUE TITLE
attach on a channel for a failed client does not fail the attach

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#73]
See https://jsbin.ably.io/anadag/7/edit for an example.

I would have expected a channel attach failure and an error to be emitted.

**Comment by paddybyers** [comment]
@SimonWoolf : are you ok to have a look at this please?

**Comment by SimonWoolf** [comment]
@paddybyers sure, will look into this & the other assigned issues next week.

**Comment by SimonWoolf** [comment]
Closing; works as expected. Previous output was the result of two interacting usage errors: putting `capability` in the `authOptions` rather than the `tokenParams` (where it had no effect), and feeding the resulting token into the first argument of the `getTokenRequest` callback rather than the second. Fixed jsbin showing correct output at https://jsbin.ably.io/anadag/9/ .
