### ISSUE TITLE
How to provide a client with a token when the server has no public endpoint?

### ISSUE THREAD

**Issue by markg85** [ably/ably-js#870]
Hi,

I'm building a small hobby-project site that lives on IPFS and is therefore fully "static". With the site i'm able to control certain parts of my home. I currently do this by using the [NKN blockchain](https://nkn.org/) and their pubsub functionality. That works because NKN works with public/private keys. My site has one pair, my server has another pair. Any messages send via NKN have the public key in there too. This allows me to whitelist a public key (on the server and client) from which i want to accept messages.

While this works just fine, i do need to move away from it for other technical reasons. 

In this scheme there is no server that needs to generate a token for me. Because of that freedom my server can literally be anywhere. I can pull the plug on it locally and spin it up on a cloud and it will work as long as the keys remain the same.

With Ably this seems to be a rather difficult concept to implement. Upon reading the documentation i see that there is basic authentication with API keys and token based authentication. It is advised to use tokens on websites and api keys on servers, i'm trying to follow that advice.

The problem i have now is that - in this scheme - my client **must** send something to the server for the authentication flow to proceed. It must do that as initial starting point and therefore **requires** my server to at least have that part publicly exposed. Or that's how i get the docs.

How do i create this initial token request step without exposing anything from the server?
Exposing my server is not an option.

Just a wild idea. Wouldn't it be cool if there were to be one free open pubsub channel that any client and server can connect to without any API keys? You could then use that publicly available channel to send those authentication requests via pubsub and handle it that way.

I'm curious about your thoughts on this technical challenging issue!
And if there's a solution for it?

Best regards,
Mark

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1449) by [Unito](https://www.unito.io)

**Comment by lmars** [comment]
@markg85 this sounds like an interesting project! This is definitely something you can achieve using Ably, but first it would be good to understand how this currently works. Since your site is on IPFS where anyone can retrieve it, where do you currently store the site's client-side private key?

**Comment by markg85** [comment]
The keys are stored in the browsers [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). That data is quite long lived and should be secure too. For my case this is perfect.

Note that this is just one way.
I am currently playing with encryption and web3 wallets (metamask) to store this data in encrypted form on IPFS and let it be decrypted by my wallet. It's a little more involved then this but it gives you a general idea of an alternative way how it can work too.

**Comment by lmars** [comment]
> The keys are stored in the browsers local storage

Ok I thought that may be the case.

So the model with Ably could be the same: store an Ably API key in local storage, and then either use it to sign a token right there in the browser, or just use the key directly with an Ably client.

This does depart from our advice to not use API keys on client-side devices, but that advice is because a typical Ably application has many different clients (e.g. customers) and it's not feasible to generate, issue, and securely store API keys for each of those clients, but in your case there is only one client (you), so a single API key issued to yourself to use in your own browser works just fine.

You may want to consider using the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) instead of local storage though, then you could use [SubtleCrypto.sign](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign) to sign an Ably token without exposing the Ably API key to the JavaScript code.

> I am currently playing with encryption and web3 wallets (metamask) to store this data in encrypted form on IPFS and let it be decrypted by my wallet

That could work the same way too (i.e. encrypt the Ably API key, store it in IPFS, then when loading the site, retrieve the encrypted key, decrypt it with your wallet, then use it as above).

**Comment by markg85** [comment]
Hi @lmars , thank you for that reply!

I was already kinda expecting it to go that route. I'm fine using the API key route but wanted to make sure that there wasn't a usable way for the token route without exposing an endpoint.

Still though, it might be interesting for Ably to investigate ways to create an Ably token without the need to expose an endpoint. As reducing endpoint needs is one step closer to a full on distributed web. Here too, the example i gave before (exposing a public pubsub room for this) is just one potential way. Another would be with blockchain tech and IPFS in very much the same way as i am going to store settings for my site. 

To elaborate slightly more on that as it's more complicated then "just encrypting". What I store on the blockchain is just 1 [CID](https://docs.ipfs.io/concepts/content-addressing/) (content identifier). I can then fetch the data belonging to that CID from IPFS. That data is asynchronously encrypted by my wallet. In this scheme no plain data is ever stored on IPFS. You can consider this data that's encrypted/decrypted by the wallet to be "metadata". That data, when decrypted, then contains a synchronous AES key (potentially also a initialization vector) and another CID to a bigger data blob which itself is encrypted by the AES key from the "metadata" and contains of all the settings for my site. I'm splitting it up because it's a best practice way to encrypt as little data as possible with asynchronous encryption because it's relatively slow.

In this very same logic an Ably token could be created too. A downside, at least in my opinion, is that each token update/renewal/whatever will be a new transaction and that will cost money. For shortly lived tokens and a lot of users that could very quickly become quite expensive, even on cheap blockchains. But that's an issue that's quite out of scope for this github question.

**Comment by lmars** [comment]
> it might be interesting for Ably to investigate ways to create an Ably token without the need to expose an endpoint

Having a server with a publicly available HTTP endpoint that can issue tokens to clients is the most typical approach, but it isn't the only approach. Ably SDK clients also support an `authCallback` option which is a function that is called when the SDK needs a token, and that function can return a token using whatever logic is appropriate for the application.

For example, as I hinted to in my previous comment, you could have an encrypted Ably API key embedded in the source of your site, and use an `authCallback` to decrypt it with your wallet and issue a token in your browser:

```js
const encryptedAblyKey = '<the encrypted Ably API Key>';

const authCallback = (tokenParams, callback) => {
  const key = wallet.decrypt(encryptedAblyKey);

  const keyName = key.split(':')[0];
  const keySecret = key.split(':')[1];

  jwt.sign(tokenParams, keySecret, { expiresIn: '60m', keyid: keyName }, callback);
};

const client = new Ably.Realtime({ authCallback });
```

> the example i gave before (exposing a public pubsub room for this) is just one potential way. Another would be with blockchain tech and IPFS in very much the same way as i am going to store settings for my site.

Given we're talking about public services though (either a public Ably channel, or communication via a public blockchain), there still needs to be a way to identify your specific client, which you've been doing so far by issuing a credential to that client (i.e. a key pair) and sharing the ID of that credential with your server (i.e. the client's public key), and so for Ably that credential can just be an Ably API key that is secured on the client using a similar mechanism to securing a key pair (e.g. local storage, Web Crypto API, TPM, crypto wallet, etc.).

If we were to better support this use case though, something that may be useful is if you could register an asymmetric key pair with Ably, and Ably then accepts tokens signed by that key pair (rather than just accepting tokens signed by an API key). With this, you could then register your client's public key and sign Ably tokens directly using your wallet.

**Comment by markg85** [comment]
Hi @lmars 

Thank you again for that informative reply!
I did get the encryption idea but seeing a example how it would be implemented does help quite a bit! Especially as i'm quite new to the Ably API.

Thank you for this insight, i'm going to play with it and see where i end up.

**Comment by owenpearson** [comment]
Closing this now as the issue appears to be resolved (thanks @lmars)
