### ISSUE TITLE
swcMinify (next.js builder) breaks Ably entirely

### ISSUE THREAD

**Issue by TheoBr** [ably/ably-js#957]
Hey guys!

Really excited to get Ably running - sadly in our existing Next.js build pipe Ably fails to run

![image](https://user-images.githubusercontent.com/6751787/163898339-61af5683-4144-41d3-855e-f0bb34bba841.png)

When I disable `swcMinify` in my next config, the build works as expected

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1785) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hi @TheoBr, thanks for reporting. This is actually an issue with NextJS https://github.com/vercel/next.js/issues/35008 and should be resolved by upgrading to a newer Next version. I'm not sure exactly which version it is fixed in but next@12.1.4 or higher should work. Let us know if you continue to have any issues.

**Comment by TheoBr** [comment]
Confirmed the version bump fixed our issues ty @owenpearson !!!
